sudo: false
language: node_js
node_js:
  - "0.12"
before_install:
  - npm install -g gulp
  - npm install -g bower
  - npm install
  - bower install
script:
  - npm run-script ci
cache:
  directories:
    - node_modules
